In [ ]:
# download
## curl?

In [136]:
from accelerate import PartialState

In [138]:
distributed_state = PartialState()

In [140]:
distributed_state.distributed_type

<DistributedType.NO: 'NO'>

In [146]:
ds['train'][0]['label']

1

In [144]:
ds['train'].to_list

AttributeError: 'Dataset' object has no attribute 'tolist'

In [141]:
distributed_state.is_main_process

True

In [80]:
from transformers import DataCollatorForLanguageModeling, AutoTokenizer, AutoModelForSequenceClassification, DataCollatorWithPadding


In [135]:
ds

DatasetDict({
    train: Dataset({
        features: ['promptID', 'pairID', 'premise', 'premise_binary_parse', 'premise_parse', 'hypothesis', 'hypothesis_binary_parse', 'hypothesis_parse', 'genre', 'label'],
        num_rows: 392702
    })
    validation_matched: Dataset({
        features: ['promptID', 'pairID', 'premise', 'premise_binary_parse', 'premise_parse', 'hypothesis', 'hypothesis_binary_parse', 'hypothesis_parse', 'genre', 'label'],
        num_rows: 9815
    })
    validation_mismatched: Dataset({
        features: ['promptID', 'pairID', 'premise', 'premise_binary_parse', 'premise_parse', 'hypothesis', 'hypothesis_binary_parse', 'hypothesis_parse', 'genre', 'label'],
        num_rows: 9832
    })
})

In [102]:
batch.labels

tensor([1, 0, 0, 0, 1, 0, 1, 0])

In [107]:
tokenizer.pad_token_id

2

In [130]:
from tqdm import tqdm

In [131]:
for i in tqdm(ds['train']):
    i['test']=1

100%|███████████████████████████████████████████████████████████████████████| 392702/392702 [00:33<00:00, 11865.45it/s]


In [134]:
ds['train'].to_json()

TypeError: Dataset.to_json() missing 1 required positional argument: 'path_or_buf'

In [132]:
ds['train']

Dataset({
    features: ['promptID', 'pairID', 'premise', 'premise_binary_parse', 'premise_parse', 'hypothesis', 'hypothesis_binary_parse', 'hypothesis_parse', 'genre', 'label'],
    num_rows: 392702
})

In [ ]:
if os.

In [113]:
model.config.pad_token_id = tokenizer.pad_token_id

In [125]:
batch.to('cuda')

{'input_ids': tensor([[    2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2,     2,     2,     2,     2,     2,     2,     2,     1,
          6097,   895, 29901,  1281,  1547,  1474,   907,   314,  2071, 25217,
           756,  1023,  6996, 13391,   448,  3234,   322,  1737,  5275, 29889,
            13,    13, 29950,  1478,   720,  6656, 29901, 10969,   322,  1737,
          5275,   526,   825,  1207,   907,   314,  2071, 25217,   664, 29889,
         29871],
        [    1,  6097,   895, 29901,   366,  1073,  2645,   278,  4259,   322,
           474,  4140,   472,   472,   596,  3233,   318, 29882,   366, 14074,
           963,   304,   278,  2446,  3233,   565,   565,   896, 11097,   304,
         17386,   278

In [114]:
with torch.no_grad():
    x = model(input_ids=batch.input_ids, labels=batch.labels)

In [117]:
import torch

In [118]:
x.logits.argmax(dim=-1)

tensor([0, 0, 1, 0, 0, 0, 0, 0])

In [119]:
import evaluate
accuracy = evaluate.load("accuracy")

In [123]:

ds['train'].select(indices=range(24))

Dataset({
    features: ['promptID', 'pairID', 'premise', 'premise_binary_parse', 'premise_parse', 'hypothesis', 'hypothesis_binary_parse', 'hypothesis_parse', 'genre', 'label'],
    num_rows: 24
})

In [120]:

ds['train'][:24]

{'promptID': [31193,
  101457,
  134793,
  37397,
  50563,
  110116,
  42487,
  1069,
  23505,
  60529,
  55785,
  11877,
  32819,
  52772,
  102489,
  81785,
  16915,
  56687,
  101211,
  62897,
  38518,
  138444,
  76011,
  78652],
 'pairID': ['31193n',
  '101457e',
  '134793e',
  '37397e',
  '50563n',
  '110116e',
  '42487n',
  '1069e',
  '23505c',
  '60529c',
  '55785e',
  '11877c',
  '32819n',
  '52772n',
  '102489c',
  '81785e',
  '16915e',
  '56687c',
  '101211c',
  '62897n',
  '38518e',
  '138444e',
  '76011c',
  '78652e'],
 'premise': ['Conceptually cream skimming has two basic dimensions - product and geography.',
  'you know during the season and i guess at at your level uh you lose them to the next level if if they decide to recall the the parent team the Braves decide to call to recall a guy from triple A then a double A guy goes up to replace him and a single A guy goes up to replace him',
  'One of our number will carry out your instructions minutely.',
  'How do you kno

In [ ]:
accuracy.compute(predictions=predicts, references=actuals)

In [ ]:
import sklearn.metrics.acc

In [52]:
from datasets import load_dataset
ds = load_dataset("nyu-mll/multi_nli")

from transformers import DataCollatorForLanguageModeling, AutoTokenizer, AutoModelForSequenceClassification, DataCollatorWithPadding, 

tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama_v1.1")
# model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama_v1.1")
if tokenizer.pad_token == None:
    tokenizer.pad_token = tokenizer.eos_token
    
def preprocess_function(examples, tokenizer):
    new_examples = {
        "input_ids": [],
        "attention_mask": [],
        "labels": [],
    }
    for premise, hypothesis, labels in zip(examples["premise"], examples["hypothesis"], examples['label']):
        tokenized = tokenizer("Premise: " + premise + "\n\nHypothesis: " + hypothesis)
        new_examples["input_ids"].append(tokenized["input_ids"])
        new_examples["attention_mask"].append(tokenized["attention_mask"])
        new_examples['labels'].append(labels)
    return new_examples


import os
num_proc = 1 #int(os.cpu_count()*0.95)
# num_proc = 2

column_names = ds['train'].column_names

train_dataset = train_dataset.map(
    lambda example : preprocess_function(example, tokenizer),
    batched=True,
    num_proc=num_proc,
    remove_columns=column_names,
)

Map:   0%|          | 0/392702 [00:00<?, ? examples/s]

In [81]:
collate_fn = DataCollatorWithPadding(tokenizer=tokenizer, padding=True, return_tensors='pt')

In [86]:
tokenizer.padding_side = 'left'

In [71]:
from transformers import AutoModelForSequenceClassification

In [99]:
model.config.num_labels

2

In [ ]:
AutoModelForSequenceClassification.from_pretrained(

In [74]:
path = "TinyLlama/TinyLlama_v1.1"a

In [95]:

import torch

In [96]:
model = AutoModelForSequenceClassification.from_pretrained(path, attn_implementation="flash_attention_2", trust_remote_code=True, torch_dtype=torch.bfloat16, %notebook)

ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.

In [87]:
from torch.utils.data import Dataset, DataLoader, RandomSampler

In [88]:
from torch.utils.data import DataLoader

In [89]:
train_dataloader = DataLoader(dataset=train_dataset, batch_size=batch_size, collate_fn=collate_fn)

In [90]:
if tokenizer.pad_token == None:
    tokenizer.pad_token = tokenizer.eos_token

In [91]:
batch = next(iter(train_dataloader))

In [93]:
batch['labels']

tensor([1, 0, 0, 0, 1, 0, 1, 0])

In [10]:
ds['train'][0]['premise']

'Conceptually cream skimming has two basic dimensions - product and geography.'

In [11]:
ds['train'][0]['hypothesis']

'Product and geography are what make cream skimming work. '

In [ ]:
'''
entailment (0), neutral (1), contradiction (2)
'''